In [21]:
from glob import glob
import os
import pandas as pd
import json

In [22]:
w0files = sorted(glob('Data\\weather\\***\\2016-*.json'))

In [23]:
w1files = sorted(glob('Data\\weather\\***\\2017-*.json'))

In [24]:
airports = ['ATL','CLT','DEN','DFW','EWR','IAH','JFK','LAS','LAX','MCO','MIA','ORD','PHX','SEA','SFO']

In [25]:
weather_data1 = []
for i in w1files:
    with open(i) as f:
        temp = json.load(f)
        for k in temp['data']['weather']:
            tempdata1 = pd.DataFrame(k['hourly'],columns=['windspeedKmph','visibility','weatherCode','precipMM','WindGustKmph','pressure','cloudcover','winddirDegree','humidity','DewPointF','tempF','time','WindChillF'])
            tempdata1['date'] = k['date']
            for a in airports:
                if a in i.split('\\'):
                    tempdata1['place'] = a 
            weather_data1 = pd.DataFrame(weather_data1.append(tempdata1))
weather_data1.reset_index()

,index,windspeedKmph,visibility,weatherCode,precipMM,WindGustKmph,pressure,cloudcover,winddirDegree,humidity,DewPointF,tempF,time,WindChillF,date,place
0,0,8,7,353,6.1,16,1021,100,100,97,50,51,0,49,2017-01-02,ATL
1,1,8,7,353,5.1,16,1020,100,99,97,50,51,100,50,2017-01-02,ATL
2,2,7,8,356,4.1,15,1020,100,99,98,51,52,200,50,2017-01-02,ATL
3,3,7,9,356,3.1,14,1020,100,99,98,51,52,300,51,2017-01-02,ATL
4,4,6,8,356,4.1,13,1020,100,92,98,52,52,400,52,2017-01-02,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131371,19,26,10,113,0.0,27,1014,0,296,70,57,67,1900,67,2017-09-30,SFO
131372,20,26,10,113,0.0,27,1014,0,298,71,58,67,2000,67,2017-09-30,SFO
131373,21,26,10,113,0.0,27,1014,0,300,73,58,67,2100,67,2017-09-30,SFO
131374,22,23,10,113,0.0,25,1014,0,302,74,58,66,2200,66,2017-09-30,SFO
131375,23,20,10,113,0.0,22,1014,0,303,75,58,66,2300,66,2017-09-30,SFO

In [139]:
weather_data1.to_csv('Data\\weather17.csv')

In [17]:
weather_data0 = []
for i in w0files[1:]:
    with open(i) as f:
        temp = json.load(f)
        for k in temp['data']['weather']:
            tempdata0 = pd.DataFrame(k['hourly'],columns=['windspeedKmph','visibility','weatherCode','precipMM','WindGustKmph','pressure','cloudcover','winddirDegree','humidity','DewPointF','tempF','time','WindChillF'])
            tempdata0['date'] = k['date']
            for a in airports:
                if a in i.split('\\'):
                    tempdata0['place'] = a 
            weather_data0 = pd.DataFrame(weather_data0.append(tempdata0))
weather_data0.reset_index()

,index,windspeedKmph,visibility,weatherCode,precipMM,WindGustKmph,pressure,cloudcover,winddirDegree,humidity,DewPointF,tempF,time,WindChillF,date,place
0,0,2,10,113,0.0,4,1018,8,197,54,51,71,0,71,2016-10-02,ATL
1,1,2,10,113,0.0,4,1018,11,202,55,51,68,100,69,2016-10-02,ATL
2,2,2,10,113,0.0,4,1018,14,208,56,51,66,200,67,2016-10-02,ATL
3,3,2,10,113,0.0,4,1017,17,213,57,51,64,300,65,2016-10-02,ATL
4,4,2,10,113,0.0,4,1017,11,233,59,51,62,400,63,2016-10-02,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130987,19,22,10,116,0.0,26,1020,51,289,80,51,58,1900,55,2016-09-30,SFO
130988,20,21,10,119,0.0,25,1020,64,291,85,52,57,2000,54,2016-09-30,SFO
130989,21,21,10,119,0.0,24,1020,77,293,90,54,56,2100,53,2016-09-30,SFO
130990,22,20,10,119,0.0,23,1020,81,294,91,54,56,2200,53,2016-09-30,SFO
130991,23,19,10,122,0.0,23,1020,86,296,92,54,56,2300,53,2016-09-30,SFO

In [19]:
weather_data0.to_csv('Data\\weather16.csv')

In [26]:
weather_df = pd.concat([weather_data0,weather_data1])
weather_df.to_csv('Data\\Weather_Data.csv')